//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAdmin.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarnTable", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceForskolaAnsoka1")]
    [System.SerializableAttribute()]
    public partial class BarnTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BefternamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BfodelsedatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BfornamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BfyrasiffrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BpostadressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BpostnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BpostortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForskolaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VefternamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VfodelsedatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VfornamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VfyrasiffrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VhemtelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VmobiltelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VpostadressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VpostnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VpostortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Befternamn {
            get {
                return this.BefternamnField;
            }
            set {
                if ((object.ReferenceEquals(this.BefternamnField, value) != true)) {
                    this.BefternamnField = value;
                    this.RaisePropertyChanged("Befternamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bfodelsedatum {
            get {
                return this.BfodelsedatumField;
            }
            set {
                if ((this.BfodelsedatumField.Equals(value) != true)) {
                    this.BfodelsedatumField = value;
                    this.RaisePropertyChanged("Bfodelsedatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bfornamn {
            get {
                return this.BfornamnField;
            }
            set {
                if ((object.ReferenceEquals(this.BfornamnField, value) != true)) {
                    this.BfornamnField = value;
                    this.RaisePropertyChanged("Bfornamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bfyrasiffror {
            get {
                return this.BfyrasiffrorField;
            }
            set {
                if ((this.BfyrasiffrorField.Equals(value) != true)) {
                    this.BfyrasiffrorField = value;
                    this.RaisePropertyChanged("Bfyrasiffror");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bpostadress {
            get {
                return this.BpostadressField;
            }
            set {
                if ((object.ReferenceEquals(this.BpostadressField, value) != true)) {
                    this.BpostadressField = value;
                    this.RaisePropertyChanged("Bpostadress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bpostnummer {
            get {
                return this.BpostnummerField;
            }
            set {
                if ((this.BpostnummerField.Equals(value) != true)) {
                    this.BpostnummerField = value;
                    this.RaisePropertyChanged("Bpostnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bpostort {
            get {
                return this.BpostortField;
            }
            set {
                if ((object.ReferenceEquals(this.BpostortField, value) != true)) {
                    this.BpostortField = value;
                    this.RaisePropertyChanged("Bpostort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Forskola {
            get {
                return this.ForskolaField;
            }
            set {
                if ((object.ReferenceEquals(this.ForskolaField, value) != true)) {
                    this.ForskolaField = value;
                    this.RaisePropertyChanged("Forskola");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vefternamn {
            get {
                return this.VefternamnField;
            }
            set {
                if ((object.ReferenceEquals(this.VefternamnField, value) != true)) {
                    this.VefternamnField = value;
                    this.RaisePropertyChanged("Vefternamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vfodelsedatum {
            get {
                return this.VfodelsedatumField;
            }
            set {
                if ((this.VfodelsedatumField.Equals(value) != true)) {
                    this.VfodelsedatumField = value;
                    this.RaisePropertyChanged("Vfodelsedatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vfornamn {
            get {
                return this.VfornamnField;
            }
            set {
                if ((object.ReferenceEquals(this.VfornamnField, value) != true)) {
                    this.VfornamnField = value;
                    this.RaisePropertyChanged("Vfornamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vfyrasiffror {
            get {
                return this.VfyrasiffrorField;
            }
            set {
                if ((this.VfyrasiffrorField.Equals(value) != true)) {
                    this.VfyrasiffrorField = value;
                    this.RaisePropertyChanged("Vfyrasiffror");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vhemtelefon {
            get {
                return this.VhemtelefonField;
            }
            set {
                if ((this.VhemtelefonField.Equals(value) != true)) {
                    this.VhemtelefonField = value;
                    this.RaisePropertyChanged("Vhemtelefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vmobiltelefon {
            get {
                return this.VmobiltelefonField;
            }
            set {
                if ((this.VmobiltelefonField.Equals(value) != true)) {
                    this.VmobiltelefonField = value;
                    this.RaisePropertyChanged("Vmobiltelefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vpostadress {
            get {
                return this.VpostadressField;
            }
            set {
                if ((object.ReferenceEquals(this.VpostadressField, value) != true)) {
                    this.VpostadressField = value;
                    this.RaisePropertyChanged("Vpostadress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vpostnummer {
            get {
                return this.VpostnummerField;
            }
            set {
                if ((this.VpostnummerField.Equals(value) != true)) {
                    this.VpostnummerField = value;
                    this.RaisePropertyChanged("Vpostnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vpostort {
            get {
                return this.VpostortField;
            }
            set {
                if ((object.ReferenceEquals(this.VpostortField, value) != true)) {
                    this.VpostortField = value;
                    this.RaisePropertyChanged("Vpostort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusTable", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceForskolaAnsoka1")]
    [System.SerializableAttribute()]
    public partial class StatusTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedomningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BfyrasiffrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KommentarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bedomning {
            get {
                return this.BedomningField;
            }
            set {
                if ((object.ReferenceEquals(this.BedomningField, value) != true)) {
                    this.BedomningField = value;
                    this.RaisePropertyChanged("Bedomning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bfyrasiffror {
            get {
                return this.BfyrasiffrorField;
            }
            set {
                if ((this.BfyrasiffrorField.Equals(value) != true)) {
                    this.BfyrasiffrorField = value;
                    this.RaisePropertyChanged("Bfyrasiffror");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kommentar {
            get {
                return this.KommentarField;
            }
            set {
                if ((object.ReferenceEquals(this.KommentarField, value) != true)) {
                    this.KommentarField = value;
                    this.RaisePropertyChanged("Kommentar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarnClass", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceForskolaAnsoka1")]
    [System.SerializableAttribute()]
    public partial class BarnClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BefternamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BfodelsedatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BfornamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BfyrasiffrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BpostadressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BpostnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BpostortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForskolaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VefternamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VfodelsedatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VfornamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VfyrasiffrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VhemtelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VmobiltelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VpostadressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VpostnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VpostortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Befternamn {
            get {
                return this.BefternamnField;
            }
            set {
                if ((object.ReferenceEquals(this.BefternamnField, value) != true)) {
                    this.BefternamnField = value;
                    this.RaisePropertyChanged("Befternamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bfodelsedatum {
            get {
                return this.BfodelsedatumField;
            }
            set {
                if ((this.BfodelsedatumField.Equals(value) != true)) {
                    this.BfodelsedatumField = value;
                    this.RaisePropertyChanged("Bfodelsedatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bfornamn {
            get {
                return this.BfornamnField;
            }
            set {
                if ((object.ReferenceEquals(this.BfornamnField, value) != true)) {
                    this.BfornamnField = value;
                    this.RaisePropertyChanged("Bfornamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bfyrasiffror {
            get {
                return this.BfyrasiffrorField;
            }
            set {
                if ((this.BfyrasiffrorField.Equals(value) != true)) {
                    this.BfyrasiffrorField = value;
                    this.RaisePropertyChanged("Bfyrasiffror");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bpostadress {
            get {
                return this.BpostadressField;
            }
            set {
                if ((object.ReferenceEquals(this.BpostadressField, value) != true)) {
                    this.BpostadressField = value;
                    this.RaisePropertyChanged("Bpostadress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bpostnummer {
            get {
                return this.BpostnummerField;
            }
            set {
                if ((this.BpostnummerField.Equals(value) != true)) {
                    this.BpostnummerField = value;
                    this.RaisePropertyChanged("Bpostnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bpostort {
            get {
                return this.BpostortField;
            }
            set {
                if ((object.ReferenceEquals(this.BpostortField, value) != true)) {
                    this.BpostortField = value;
                    this.RaisePropertyChanged("Bpostort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Forskola {
            get {
                return this.ForskolaField;
            }
            set {
                if ((object.ReferenceEquals(this.ForskolaField, value) != true)) {
                    this.ForskolaField = value;
                    this.RaisePropertyChanged("Forskola");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vefternamn {
            get {
                return this.VefternamnField;
            }
            set {
                if ((object.ReferenceEquals(this.VefternamnField, value) != true)) {
                    this.VefternamnField = value;
                    this.RaisePropertyChanged("Vefternamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vfodelsedatum {
            get {
                return this.VfodelsedatumField;
            }
            set {
                if ((this.VfodelsedatumField.Equals(value) != true)) {
                    this.VfodelsedatumField = value;
                    this.RaisePropertyChanged("Vfodelsedatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vfornamn {
            get {
                return this.VfornamnField;
            }
            set {
                if ((object.ReferenceEquals(this.VfornamnField, value) != true)) {
                    this.VfornamnField = value;
                    this.RaisePropertyChanged("Vfornamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vfyrasiffror {
            get {
                return this.VfyrasiffrorField;
            }
            set {
                if ((this.VfyrasiffrorField.Equals(value) != true)) {
                    this.VfyrasiffrorField = value;
                    this.RaisePropertyChanged("Vfyrasiffror");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vhemtelefon {
            get {
                return this.VhemtelefonField;
            }
            set {
                if ((this.VhemtelefonField.Equals(value) != true)) {
                    this.VhemtelefonField = value;
                    this.RaisePropertyChanged("Vhemtelefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vmobiltelefon {
            get {
                return this.VmobiltelefonField;
            }
            set {
                if ((this.VmobiltelefonField.Equals(value) != true)) {
                    this.VmobiltelefonField = value;
                    this.RaisePropertyChanged("Vmobiltelefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vpostadress {
            get {
                return this.VpostadressField;
            }
            set {
                if ((object.ReferenceEquals(this.VpostadressField, value) != true)) {
                    this.VpostadressField = value;
                    this.RaisePropertyChanged("Vpostadress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vpostnummer {
            get {
                return this.VpostnummerField;
            }
            set {
                if ((this.VpostnummerField.Equals(value) != true)) {
                    this.VpostnummerField = value;
                    this.RaisePropertyChanged("Vpostnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vpostort {
            get {
                return this.VpostortField;
            }
            set {
                if ((object.ReferenceEquals(this.VpostortField, value) != true)) {
                    this.VpostortField = value;
                    this.RaisePropertyChanged("Vpostort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusClass", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceForskolaAnsoka1")]
    [System.SerializableAttribute()]
    public partial class StatusClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedomningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BfyrasiffrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KommentarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bedomning {
            get {
                return this.BedomningField;
            }
            set {
                if ((object.ReferenceEquals(this.BedomningField, value) != true)) {
                    this.BedomningField = value;
                    this.RaisePropertyChanged("Bedomning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bfyrasiffror {
            get {
                return this.BfyrasiffrorField;
            }
            set {
                if ((this.BfyrasiffrorField.Equals(value) != true)) {
                    this.BfyrasiffrorField = value;
                    this.RaisePropertyChanged("Bfyrasiffror");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kommentar {
            get {
                return this.KommentarField;
            }
            set {
                if ((object.ReferenceEquals(this.KommentarField, value) != true)) {
                    this.KommentarField = value;
                    this.RaisePropertyChanged("Kommentar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateBarn", ReplyAction="http://tempuri.org/IService1/CreateBarnResponse")]
        bool CreateBarn(WebApplicationAdmin.ServiceReference2.BarnTable NyBarn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateBarn", ReplyAction="http://tempuri.org/IService1/CreateBarnResponse")]
        System.Threading.Tasks.Task<bool> CreateBarnAsync(WebApplicationAdmin.ServiceReference2.BarnTable NyBarn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateStatus", ReplyAction="http://tempuri.org/IService1/CreateStatusResponse")]
        bool CreateStatus(WebApplicationAdmin.ServiceReference2.StatusTable NyStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateStatus", ReplyAction="http://tempuri.org/IService1/CreateStatusResponse")]
        System.Threading.Tasks.Task<bool> CreateStatusAsync(WebApplicationAdmin.ServiceReference2.StatusTable NyStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBarn", ReplyAction="http://tempuri.org/IService1/DeleteBarnResponse")]
        bool DeleteBarn(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBarn", ReplyAction="http://tempuri.org/IService1/DeleteBarnResponse")]
        System.Threading.Tasks.Task<bool> DeleteBarnAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatus", ReplyAction="http://tempuri.org/IService1/DeleteStatusResponse")]
        bool DeleteStatus(int Fyrasiffror);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatus", ReplyAction="http://tempuri.org/IService1/DeleteStatusResponse")]
        System.Threading.Tasks.Task<bool> DeleteStatusAsync(int Fyrasiffror);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBarnLista", ReplyAction="http://tempuri.org/IService1/GetBarnListaResponse")]
        WebApplicationAdmin.ServiceReference2.BarnClass[] GetBarnLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBarnLista", ReplyAction="http://tempuri.org/IService1/GetBarnListaResponse")]
        System.Threading.Tasks.Task<WebApplicationAdmin.ServiceReference2.BarnClass[]> GetBarnListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStatusLista", ReplyAction="http://tempuri.org/IService1/GetStatusListaResponse")]
        WebApplicationAdmin.ServiceReference2.StatusClass[] GetStatusLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStatusLista", ReplyAction="http://tempuri.org/IService1/GetStatusListaResponse")]
        System.Threading.Tasks.Task<WebApplicationAdmin.ServiceReference2.StatusClass[]> GetStatusListaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplicationAdmin.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplicationAdmin.ServiceReference2.IService1>, WebApplicationAdmin.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateBarn(WebApplicationAdmin.ServiceReference2.BarnTable NyBarn) {
            return base.Channel.CreateBarn(NyBarn);
        }
        
        public System.Threading.Tasks.Task<bool> CreateBarnAsync(WebApplicationAdmin.ServiceReference2.BarnTable NyBarn) {
            return base.Channel.CreateBarnAsync(NyBarn);
        }
        
        public bool CreateStatus(WebApplicationAdmin.ServiceReference2.StatusTable NyStatus) {
            return base.Channel.CreateStatus(NyStatus);
        }
        
        public System.Threading.Tasks.Task<bool> CreateStatusAsync(WebApplicationAdmin.ServiceReference2.StatusTable NyStatus) {
            return base.Channel.CreateStatusAsync(NyStatus);
        }
        
        public bool DeleteBarn(int i) {
            return base.Channel.DeleteBarn(i);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBarnAsync(int i) {
            return base.Channel.DeleteBarnAsync(i);
        }
        
        public bool DeleteStatus(int Fyrasiffror) {
            return base.Channel.DeleteStatus(Fyrasiffror);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStatusAsync(int Fyrasiffror) {
            return base.Channel.DeleteStatusAsync(Fyrasiffror);
        }
        
        public WebApplicationAdmin.ServiceReference2.BarnClass[] GetBarnLista() {
            return base.Channel.GetBarnLista();
        }
        
        public System.Threading.Tasks.Task<WebApplicationAdmin.ServiceReference2.BarnClass[]> GetBarnListaAsync() {
            return base.Channel.GetBarnListaAsync();
        }
        
        public WebApplicationAdmin.ServiceReference2.StatusClass[] GetStatusLista() {
            return base.Channel.GetStatusLista();
        }
        
        public System.Threading.Tasks.Task<WebApplicationAdmin.ServiceReference2.StatusClass[]> GetStatusListaAsync() {
            return base.Channel.GetStatusListaAsync();
        }
    }
}
