//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceForskolaAnsoka1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarnTable
    {
        public int Bfyrasiffror { get; set; }
        public int Bfodelsedatum { get; set; }
        public string Bfornamn { get; set; }
        public string Befternamn { get; set; }
        public string Bpostadress { get; set; }
        public string Bpostort { get; set; }
        public int Bpostnummer { get; set; }
        public int Vfyrasiffror { get; set; }
        public int Vfodelsedatum { get; set; }
        public string Vfornamn { get; set; }
        public string Vefternamn { get; set; }
        public int Vhemtelefon { get; set; }
        public int Vmobiltelefon { get; set; }
        public string Vpostadress { get; set; }
        public string Vpostort { get; set; }
        public int Vpostnummer { get; set; }
        public string Forskola { get; set; }
    }
}
