//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceForskolaAnsoka1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusTable
    {
        public int Bfyrasiffror { get; set; }
        public string Bedomning { get; set; }
        public System.DateTime Datum { get; set; }
        public string Kommentar { get; set; }
    }
}
